server:
  port: 8104
spring:
  application:
    name: form
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hltxcloud?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 122654
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.101.111
    port: 6379
    password: 123456
    timeout: 300
    pool:
      max-wait: -1
      max-idle: 5
      min-idle: 0
      max-active: 20
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hltx.beans
rocketmq:
  producer:
    group: producer_bank2
  name-server: 127.0.0.1:9876
upload:
  imgpath: G:/img/upload/img/
  imgmaxsize: 10485760
  videopath: G:/img/upload/video/
  videomaxsize: 104857600